[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[build.environment]
  NEXT_PUBLIC_BASE_PATH = "/"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"
