name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps

    - name: Start server in background
      run: |
        nohup npm run dev > server.log 2>&1 &
        sleep 15  # Give the server time to start
        # Check if server is running
        curl -s http://localhost:3000 || (cat server.log && exit 1)

    - name: Run Playwright tests
      run: |
        # Run only the GitHub Actions compatibility test
        npx playwright test tests/github-actions.spec.js
      env:
        # Increase Node.js memory limit
        NODE_OPTIONS: --max_old_space_size=4096

    - name: Collect server logs
      if: failure()
      run: |
        # Collect any server logs for debugging
        cat server.log || echo "No server logs found"

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload test results on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-results
        path: |
          test-results/
          server.log
        retention-days: 7

    # Slack notification is commented out until webhook is configured
    # - name: Notify Slack on failure
    #   if: failure()
    #   uses: 8398a7/action-slack@v3
    #   with:
    #     status: ${{ job.status }}
    #     fields: repo,message,commit,author,action,eventName,ref,workflow
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
